# Generated by Django 3.2.7 on 2021-09-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='helminthsImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='test',
            name='lfImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='test',
            name='onchoImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='test',
            name='schistoImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
