# Generated by Django 3.2.7 on 2021-09-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210902_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='helminths',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='lf',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
