# Generated by Django 3.2.7 on 2021-09-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210907_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='enteredAt',
            new_name='createdAt',
        ),
    ]
