# Generated by Django 3.2.7 on 2021-09-09 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_enteredat_test_createdat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
