# Generated by Django 3.2.7 on 2021-09-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210916_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='helcount',
        ),
        migrations.RemoveField(
            model_name='test',
            name='helnc',
        ),
        migrations.RemoveField(
            model_name='test',
            name='helpc',
        ),
        migrations.RemoveField(
            model_name='test',
            name='lfcount',
        ),
        migrations.RemoveField(
            model_name='test',
            name='lfnc',
        ),
        migrations.RemoveField(
            model_name='test',
            name='lfpc',
        ),
        migrations.RemoveField(
            model_name='test',
            name='ocount',
        ),
        migrations.RemoveField(
            model_name='test',
            name='onc',
        ),
        migrations.RemoveField(
            model_name='test',
            name='opc',
        ),
        migrations.RemoveField(
            model_name='test',
            name='schcount',
        ),
        migrations.RemoveField(
            model_name='test',
            name='scnc',
        ),
        migrations.RemoveField(
            model_name='test',
            name='scpc',
        ),
    ]
