# Generated by Django 3.2.7 on 2021-09-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210916_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
